= Jakarta Faces 4.0 Container
:linkcss: 
:page-layout: feature
:nofooter: 

// tag::description[]
This feature enables CDI integrations for web applications that use the Jakarta Faces 4.0 framework. This feature includes only container integration code for Jakarta Faces but does not provide any API or implementation. To use this feature, the Jakarta Faces interface and implementation must be packaged within each web application.

// end::description[]

include::./facesContainer/description.adoc[opts=optional]
include::./facesContainer-4.0/description.adoc[opts=optional]

// tag::enable[]
== Enabling this feature
To enable the Jakarta Faces 4.0 Container feature, add the following element declaration into your `server.xml` file, inside the `featureManager` element:


----
<feature>facesContainer-4.0</feature>
----
// end::enable[]

include::./facesContainer/examples.adoc[opts=optional]
include::./facesContainer-4.0/examples.adoc[opts=optional]

// tag::apis[]
// end::apis[]
// tag::requirements[]

== Features that this feature enables
* feature:cdi-4.0[]
* feature:expressionLanguage-5.0[]
* feature:jndi-1.0[]
* feature:servlet-6.0[]
* feature:websocket-2.1[]
// end::requirements[]
// tag::java-versions[]

== Supported Java versions

* JavaSE-11.0
* JavaSE-17.0
* JavaSE-21.0
* JavaSE-23.0
// end::java-versions[]
// tag::platform-versions[]

== Platform Versions

* jakartaee-10.0
// end::platform-versions[]
// tag::dependencies[]
// end::dependencies[]
// tag::feature-require[]

== Developing a feature that depends on this feature
If you are developing a feature that depends on this feature, include the following item in the `Subsystem-Content` header in your feature manifest file.


[source,]
----
io.openliberty.facesContainer-4.0; type="osgi.subsystem.feature"
----
// end::feature-require[]
// tag::spi[]
// end::spi[]
