= Jakarta JSON Processing 2.0 Container
:linkcss: 
:page-layout: feature
:nofooter: 

// tag::description[]
The Jakarta API for JSON Processing (JSON-P) feature provides a standardized method for constructing and manipulating data to be rendered in JavaScript Object Notation (JSON). When this feature is enabled, there is no built-in JSON-P provider. Instead, configure a JSON-P provider via a <bell> which points at a library containing the JSON-P provider JAR file(s).

// end::description[]

include::./jsonpContainer/description.adoc[opts=optional]
include::./jsonpContainer-2.0/description.adoc[opts=optional]

// tag::enable[]
== Enabling this feature
To enable the Jakarta JSON Processing 2.0 Container feature, add the following element declaration into your `server.xml` file, inside the `featureManager` element:


----
<feature>jsonpContainer-2.0</feature>
----
// end::enable[]

include::./jsonpContainer/examples.adoc[opts=optional]
include::./jsonpContainer-2.0/examples.adoc[opts=optional]

// tag::apis[]

== Standard API packages provided by this feature
* javadoc:jakarta.json[]
* javadoc:jakarta.json.spi[]
* javadoc:jakarta.json.stream[]
// end::apis[]
// tag::requirements[]

== Features that this feature enables
* feature:bells-1.0[]
// end::requirements[]
// tag::java-versions[]

== Supported Java versions

* JavaSE-1.8
* JavaSE-11.0
* JavaSE-17.0
* JavaSE-21.0
* JavaSE-23.0
// end::java-versions[]
// tag::platform-versions[]

== Platform Versions

* jakartaee-9.1
// end::platform-versions[]
// tag::dependencies[]
// end::dependencies[]
// tag::feature-require[]

== Developing a feature that depends on this feature
If you are developing a feature that depends on this feature, include the following item in the `Subsystem-Content` header in your feature manifest file.


[source,]
----
io.openliberty.jsonpContainer-2.0; type="osgi.subsystem.feature"
----
// end::feature-require[]
// tag::spi[]
// end::spi[]
